kind: ConfigMap
apiVersion: v1
metadata:
  name: appconfig
data:
        DnsProvider: "AzurePrivateDNS"
        subscription_id: "xxxxxxxx-xxxx-xxxxx-xxxxxxxxxxxxxxxxx"
        ResourceGroup: "resourcegroupname"
        DnsZone: "domainname.local"
        TENANT_ID: "xxxxxxxx-xxxx-xxxxx-xxxxxxxxxxxxxxxxx"
        CLIENT: "xxxxxxxx-xxxx-xxxxx-xxxxxxxxxxxxxxxxx"
        KEY: "xxxxxxxx-xxxx-xxxxx-xxxxxxxxxxxxxxxxx"
